extends@: default

form:
  fields:
    
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT

          fields:
            header.smallTitle:
              type: text
              autofocus: true
              style: vertical
              label: Small Upper Title
        
        holaSetings:
          type: tab
          title: Hola Settings

          fields:
            background:
              type: section
              title: Section Background Color
              underline: true
            header.sectionBackground:
              type: selectize
              label: Additional Section Background Class
              description: For Gray Background Please Use Class 'grey-section' for White Background leave field empty. 
            serviceSection:
              type: section
              title: Services
              text: 'Icon Bank: https://iconmonstr.com/iconicfont/'
              underline: true
            header.services:
              type: list
              style: vertical
              label: Service Item
              fields:
                .icon:
                  type: iconpicker
                  label: Icon
                .title:
                  type: text
                  label: Title
                .description:
                  type: textarea
                  label: Description